### ISSUE TITLE
test, requirements

### ISSUE THREAD

**Issue by sassbalint** [badicsalex/hun_law#14]
1.
```bash
.venv/bin/pip install attr
```
was needed for me. This should be in `requirements.txt`, I guess.

2.
```bash
./generate_output.py json 2013/31
```
did not work for me.

```bash
.venv/bin/python3 generate_output.py json 2013/31
```
did work instead.
(Maybe because I run `create_venv.sh` while `miniconda` was activated and the default python remained `miniconda`'s somehow.)

**Comment by badicsalex** [comment]
Interesting, "attrs" is already in requirements. I've just tried create_venv.sh, and it worked out of the box.

Also, did you activate the venv by "source .venv/bin/activate" before trying to run ./generate_output?

Calling with .venv/bin/python3 directly is also correct though.

Also, running the project with simple CPython will be unbeareably slow, so other than trying things out, you should really use PyPy... but it will not work with the supplied requirements.txt, because mypy cannot be installed to pypy... Maybe I should do something about that.

**Comment by badicsalex** [comment]
Now create_venv creates venv-pypy, if pypy is installed, which is the recommended way of running tests and generate_output.

**Comment by sassbalint** [comment]
:facepalm: Did not activate `.venv`...
Everything is fine.
Can be closed.

**Comment by badicsalex** [comment]
It's okay, at least I've finally fixed requirements and create_venv
